# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8081

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.254:3308/gyparty_20181127?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: ~~GYcsfwq2017
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

